# SemeloOS - mkinitcpio.conf
# PENTING: Hook 'archiso' wajib ada untuk live boot dari SquashFS!

MODULES=()
BINARIES=()
FILES=()

# archiso hook HARUS ada untuk live boot bisa Switch Root ke SquashFS
HOOKS=(base systemd archiso sd-vconsole modconf kms block filesystems)
